apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: waiyanbhonemyint/product-service:latest
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-service-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: product-service-secret
                  key: DB_HOST